### ISSUE TITLE
Why is the evaluation method for Alpaca the same as for llama？

### ISSUE THREAD

**Issue by 2018211801** [allenai/open-instruct#16]
I think it is unfair!

**Comment by hamishivi** [comment]
Hi, our focus for this work was evaluating instruction-tuned models, rather than base models. Hence, the llama evaluations are more ways to show how different instruction-tuning datasets affect the base model, rather than showing that llama + training is 'better' than llama without instruction training (although, it is easier to prompt instruction-tuned models).
