### ISSUE TITLE
TypeError of import operation of run_eval.py

### ISSUE THREAD

**Issue by kelvennn** [allenai/open-instruct#17]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "open-instruct/eval/mmlu/run_eval.py", line 11, in <module>
    from eval.utils import get_next_word_predictions, load_hf_lm_and_tokenizer, query_openai_chat_model
  File "open-instruct/eval/utils.py", line 10, in <module>
    from eval.dispatch_openai_requests import dispatch_openai_chat_requesets, dispatch_openai_prompt_requesets
  File "open-instruct/eval/dispatch_openai_requests.py", line 11, in <module>
    messages_list: list[list[dict[str,Any]]],
TypeError: 'type' object is not subscriptable

```
async def dispatch_openai_chat_requesets(
    messages_list: list[list[dict[str,Any]]],
    model: str,
    **completion_kwargs: Any,
) -> list[str]:

    async_responses = [
        openai.ChatCompletion.acreate(
            model=model,
            messages=x,
            **completion_kwargs,
        )
        for x in messages_list
    ]
    return await asyncio.gather(*async_responses)
```

why the typeError occur when importing?

**Comment by hamishivi** [comment]
Ah, this is because `list[str]` is only a valid typehint in [Python 3.9 and older](https://stackoverflow.com/questions/75202610/typeerror-type-object-is-not-subscriptable-python), but you're using python 3.8. Changing the typehints to use `List` instead, or using a newer version of python, should fix things (afaik we used python 3.9). I'll make a PR to fix this up, since using `List` is more consistent with the rest of the codebase.
