### ISSUE TITLE
Commands for model evaluation

### ISSUE THREAD

**Issue by mutiann** [allenai/open-instruct#255]
May I know how are the model reported in the paper evaluated, or what are the exact evaluation commands?

Specifically, the model `open-instruct-pythia-6.9b-tulu` reports 33.4 F1 on TydiQA-GP, but when using `eval/tydiqa/run_eval.py` with options `--data_dir data/eval/tydiqa --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path allenai/open-instruct-pythia-6.9b-tulu --eval_batch_size 2 --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --model_name_or_path allenai/open-instruct-pythia-6.9b-tulu`
, as in `/scripts/eval/tydiqa.sh`, the results show an F1 of around 28 only.

**Comment by hamishivi** [comment]
Hi! I checked our old experiment logs, and that command seems correct, and I see use getting 33 F1. However, rerunning on our more recent codebase, I do indeed only get 28 F1. Precisely, we ran:
```bash
python -m eval.tydiqa.run_eval --data_dir /data/tydiqa/ --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --save_dir /output/ --model /model --tokenizer_name_or_path /model --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format
```

I'll note we have made a number of changes to our codebase since that first paper. One such change is here: https://github.com/allenai/open-instruct/commit/4a2e9dd0c1236f8cc0cdd15e5316e7c371a16624#diff-05fff9bea7c4964d7ee3b55bc26c41a6c4193fd97dd7386dec6ea055f300e985
This commit changes the choice of samples for tydiqa, from random to deterministic. Running the above command on the current codebase, I get 28 F1 matching your results. However, changing the change made in this commit (removing the `sorted`), I get 33.1 F1, better matching our reported score (and then 34.4, 38.1 F1 on 2 repeated reruns - crazy variance!) . This is a case where the choice of few-shot samples appears to have a significant impact on performance. With the new change, the choice of few-shot examples should be better (and I thiiiink this was in effect for the Tulu 2 paper onwards).

So believe this is likely the cause of the issue - hope that helps! We hope to better test our robustness to different few-shot/prompt choices in the future.
