### ISSUE TITLE
About cite/ack to OpenRLHF in README.md or paper.

### ISSUE THREAD

**Issue by hijkzzz** [allenai/open-instruct#446]
Thank you for the fantastic work! It’s great to see OpenRLHF has contributed to this project. Could we kindly request you to add a citation/ack to OpenRLHF in the README.md (or clarify in the paper) to help us promote our project?

I’d also like to mention that about 80% of the RLHF infrastructure code in TULU-v3 is based on OpenRLHF, with some modifications and restructuring (such as https://github.com/allenai/open-instruct/blob/main/open_instruct/ppo_vllm_thread_ray_gtrl.py)

This also clarifies that the RLHF infrastructure of TULU-v3 is based on OpenRLHF, but the current paper does not make this clear. 
![image](https://github.com/user-attachments/assets/cc63346b-14dc-48d6-ba3e-beda25a5d545)
Thanks！

**Comment by vwxyzjn** [comment]
Hi @hijkzzz, 

We would be happy to acknowledge OpenRLHF, which is an amazing open-source project. I've updated our README.md to include an [acknowledgement section](https://github.com/allenai/open-instruct/?tab=readme-ov-file#acknowledgements).

For transparency, I want to clarify our RLHF infrastructure's lineage:
* Our core PPO infrastructure was originally based on OpenAI's RLHF implementations:
    *  [lm-human-preferences](https://github.com/openai/lm-human-preferences), which we reproduced in [vwxyzjn/lm-human-preference-details](https://github.com/vwxyzjn/lm-human-preference-details).
    * [summarize-from-feedback](https://github.com/openai/summarize-from-feedback), which we reproduced in [vwxyzjn/summarize_from_feedback_details](https://github.com/vwxyzjn/summarize_from_feedback_details). Most of our PPO code are adapted from [summarize_from_feedback_details/ppo.py](https://github.com/vwxyzjn/summarize_from_feedback_details/blob/main/summarize_from_feedback_details/ppo.py)
* OpenRLHF has been invaluable in helping us scale to 70B models. Your ray + vllm broadcast approach is particularly elegant - it scales much better than our initial attempt at [direct vLLM weight loading](https://github.com/allenai/open-instruct/blob/c80c4049ef4c53f440ee333f7e80c9e97f1749b1/open_instruct/ppo_vllm_thread.py#L338).

We've made sure to properly attribute OpenRLHF through:

* Citation in our paper: "we also adapted model allocation techniques from existing distributed RLHF frameworks (OpenRLHF)"
* Code comments at:

https://github.com/allenai/open-instruct/blob/c80c4049ef4c53f440ee333f7e80c9e97f1749b1/open_instruct/ppo_vllm_thread_ray_gtrl.py#L14-L29
https://github.com/allenai/open-instruct/blob/c80c4049ef4c53f440ee333f7e80c9e97f1749b1/open_instruct/vllm_utils2.py#L16 

Regarding licensing, I've followed OpenRLHF's [instructions](https://github.com/OpenRLHF/OpenRLHF/blob/460477d628751bfaa95297af2763f2fd729ecd20/LICENSE#L178-L189), but noticed the Copyright [yyyy] [name of copyright owner] field is unfilled. Please let me know if you'd like this updated.

While we directly utilized OpenRLHF's code for scaling, our core PPO setup differs in many ways. For example, we 1) shard all the models equally across processes, 2) our vLLM inference runs through the entire batch at once as opposed to splitting it up using `micro_rollout_batch_size`, and 3) our setup is asynchronous: we run training / inference concurrently, and always learn from the second latest policy.

While we leveraged OpenRLHF's scaling approach, our RLHF implementation differs in several key aspects:

* We shard all the models equally across processes
* We do full-batch vLLM inference rather than using micro_rollout_batch_size
* Our setup is asynchronous: we run training / inference concurrently, and always learn from the second latest policy.

We greatly respect OpenRLHF's contributions to the field and are committed to proper attribution. Please let us know if you have any additional thoughts or questions.

**Comment by natolambert** [comment]
+1 on Costa, also answered via email. I think we're at a pretty fair spot and appreciate and highlight your work. I think counting contributions in percentages like that really works, unless all we did was copy the files in their entirety.

**Comment by hijkzzz** [comment]
Hi we also `do full-batch vLLM inference rather than using micro_rollout_batch_size`
We also use a lot of PPO implementation tricks.
the `asynchronous` is developed by your repo.
However, thank you for your cooperation.
