### ISSUE TITLE
[Question] Code for DPO Loss is not length normalised?

### ISSUE THREAD

**Issue by carlos-gemmell** [allenai/open-instruct#483]
Hi Tulu team! Thanks for the great work!

As I read the paper I saw the insight into DPO length normalisation, but when digging into the code I didn't see any normalisation term. 

https://github.com/allenai/open-instruct/blob/26b7325903813dd05ed7f4f04fa49f2794ef3b97/open_instruct/dpo_utils.py#L62-L74

Here is the original DPO equation followed by the length normalised form from the Tulu 3 Technical Report.

<img width="881" alt="image" src="https://github.com/user-attachments/assets/43dd358c-6a87-4601-9395-aa7cbe088506" />

Its likely I may be missing something obvious, thus I wanted to check with you all. Hope that's alright!
Thanks again for all the hard work! (• ◡•)

**Comment by natolambert** [comment]
Hey @carlos-gemmell -- I've gone down this rabbit hole before. The averaging is handled elsewhere. 

The "is response length" normalized tag is set here: https://github.com/allenai/open-instruct/blob/26b7325903813dd05ed7f4f04fa49f2794ef3b97/open_instruct/dpo_tune.py#L956

and in `dpo_tune.py` rather than `utils`, computation is passed through forward here: https://github.com/allenai/open-instruct/blob/26b7325903813dd05ed7f4f04fa49f2794ef3b97/open_instruct/dpo_tune.py#L962 

This passes into [`concatenated_forward`](https://github.com/allenai/open-instruct/blob/26b7325903813dd05ed7f4f04fa49f2794ef3b97/open_instruct/dpo_utils.py#L225) that is finally averaged here: https://github.com/allenai/open-instruct/blob/26b7325903813dd05ed7f4f04fa49f2794ef3b97/open_instruct/dpo_utils.py#L167

Hope this looks right...
