### ISSUE TITLE
minor difference between results in paper and my reproducing results

### ISSUE THREAD

**Issue by lucywang720** [allenai/open-instruct#70]
looks like there Is always a minor gap between your results and mine. 
tydiQA:
    llama-7b:    "average": {
        "f1": 37.98539743712254,
        "exact_match": 25.333333333333332
    }
    tulu-7b:     "average": {
        "f1": 43.70682780615583,
        "exact_match": 30.0
    }

GSM:
    llama-7b:{
    "exact_match": 0.08
}
    

why I can't reach the answer? for llama-7b, I download the llama-7b-hf model from HuggingFace at https://huggingface.co/yahma/llama-7b-hf/tree/main
for tulu-7b, I download at https://huggingface.co/allenai/tulu-7b and run the code:python scripts/weight_diff.py recover --path_raw ./llama-7b-hf --path_tuned ./tulu-7b-diff --path_diff ./tulu-7b

and I modify nothing except the batch_size for memory limit, but I don't think it will influence the output.

so can you tell me what's going wrong? I download the code at 10.8

**Comment by Stycoo** [comment]
The issue has been resolved. I made changes according to the instructions in the requirements.txt regarding the transformers bug, and now I can obtain normal evaluation scores.

**Comment by hamishivi** [comment]
Hi,

1. Some variation is expected, since generation can sometimes be a bit non-deterministic, even when trying to reduce all sources of variance. Your reported results here are within 1 point of performance on TydiQA, and within 2 points for GSM8k. I think this is okay, and probably this is not a significant difference.

2. Did you run this with llama 1 or llama 2? We found llama 1 gets 31.5%. You should also evaluate base models without any chat formatting, the command we used is like:
```
python -m eval.mmlu.run_eval \
    --ntrain 0 \
    --data_dir data/eval/mmlu \
    --save_dir results/mmlu/llama-7B-0shot \
    --model_name_or_path <your_path>/hf_llama_models/7B \
    --tokenizer_name_or_path <your_path>/hf_llama_models/7B \
    --eval_batch_size 4 \
    --load_in_8bit
    ```
