### ISSUE TITLE
Cannot reproduce llama2-7b MMLU score

### ISSUE THREAD

**Issue by harryhan618** [allenai/open-instruct#75]
Hello! Thank you for this repo!
I am evaluating the model `meta-llama/Llama-2-7b-hf` on MMLU dataset.

The command is `python -m eval.mmlu.run_eval --ntrain 5 --data_dir data/eval/mmlu --save_dir results/mmlu/llama2-7B-5shot --model_name_or_path meta-llama/Llama-2-7b-hf --tokenizer_name_or_path meta-llama/Llama-2-7b-hf --eval_batch_size 8`.
But I got the result is 0.259

While I change `eval_batch_size` to 1, the result is 0.459, which is the exact value reported by llama2 paper.

I'm wondering what's going on?

Thank you!

**Comment by yizhongw** [comment]
Hi @harryhan618 , this is because a left padding issue in the transformers library. See the discussions [here](https://github.com/huggingface/transformers/pull/25284). 

This PR hasn't been merged to the main branch of transformers, but we have updated our `requirements.txt` to use our own fork with the fix. I think your issue can be fixed after you reinstall the latest `requirements.txt`.

**Comment by harryhan618** [comment]
LOL, it's wired that when batch size = 1 will get the expect evaluation result.

Thank you for your reply!
