### ISSUE TITLE
about SFT dataset and dataset ratio

### ISSUE THREAD

**Issue by huliang2016** [allenai/open-instruct#76]
I'm curious:
1. how is the SFT dataset selected?
2. how is the data ratio determined? maybe based on testset performance?

**Comment by hamishivi** [comment]
Hi, our initial SFT dataset mixture was selected through examining a set of available datasets, and using the most promising ones. We didn't particularly tune the dataset ratios, with the one exception of sampling more from the CoT mixture of FLAN, since we found otherwise CoT performance in general dropped.

You can see details on how well each component dataset mixture performed in [our paper](https://arxiv.org/abs/2306.04751).

For our v2 mixture, we added some new popular SFT datasets (e.g. LIMA, WizardLM), and downsampled datasets to reduce the overall size of the mixture. We found this new mixture performs much better - we will have proper results out soon for it!

**Comment by huliang2016** [comment]
thanks, that's very impressive.
