### ISSUE TITLE
The alpaca eval is not working can't reproduce

### ISSUE THREAD

**Issue by sanyalsunny111** [allenai/open-instruct#83]
Hey @yizhongw great work.

This isn't working i.e. no such file in the repo 
`python eval/alpaca_farm_eval.py --model <model> --batch_size 8`

I guess you are pointing to below but this script also not working
`python eval/alpaca_farm/run_eval.py --model openlm-research/open_llama_3b --batch_size 8`

also if possible provide a tutorial to perform alpaca eval

**Comment by yizhongw** [comment]
Hi @sanyalsunny111 thanks for pointing this out. We need to update our readme and the command there is a bit outdated.

You can refer to the demo scripts [here](https://github.com/allenai/open-instruct/blob/main/scripts/eval/alpaca_farm.sh) for running alpaca eval.

**Comment by sanyalsunny111** [comment]
Hey thank you very much. I am now running openLLaMA-3B on A6000 but it is taking more than 24 hours even with 8 bit.

**Comment by hamishivi** [comment]
I recommend using VLLM if you can (it's significantly faster than HF generation). Otherwise, try setting `max_new_tokens` to a lower value. Especially for smaller models, the models can end up generating endless long repetitive text, which results in slow generation times. Reducing the number of max tokens can help reduce this slowdown.

If you are running this with a base model, this will usually always happen - since base models usually are not trained to stop generating, they will always generate the maximum allowed number of tokens...
